import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next App for Accenture Carpet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="About us">
        <div className="h-full flex flex-wrap justify-center content-center">
          <h1>About us</h1>
        </div>
      </Layout>
    </>
  )
}

export default Home
